import type{DeviceRecording}from"./page";

export type ProfessionalDocumentKind="ata"|"resumo"|"acoes"|"decisoes";

const esc=(value:string)=>value.replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]!));
const list=(items:string[],empty:string)=>items.length?`<ul>${items.map(item=>`<li>${esc(item)}</li>`).join("")}</ul>`:`<p class="empty">${esc(empty)}</p>`;
const rows=(recording:DeviceRecording)=>({
 decisions:(recording.decisions||[]).filter(x=>x.kind==="decisão").map(x=>x.text),
 pending:(recording.decisions||[]).filter(x=>x.kind==="pendência").map(x=>x.text),
 blockers:(recording.decisions||[]).filter(x=>x.kind==="bloqueio").map(x=>x.text)
});

export function openProfessionalDocument(recording:DeviceRecording,kind:ProfessionalDocumentKind){
 const labels={ata:"Ata da reunião",resumo:"Resumo executivo",acoes:"Matriz de ações",decisoes:"Decisões e bloqueios"};
 const d=rows(recording),participants=(recording.participants||"").split(/[,;\n]/).map(x=>x.trim()).filter(Boolean);
 const sections:Record<ProfessionalDocumentKind,string>={
  ata:`<section><h2>1. Identificação</h2><div class="info"><p><b>Setor/local</b>${esc(recording.department||"Não informado")}</p><p><b>Data e horário</b>${esc(recording.meetingDate||recording.createdAt)} · ${esc(recording.meetingTime||"Não informado")}</p></div></section><section><h2>2. Participantes</h2>${list(participants,"Participantes não informados.")}</section><section><h2>3. Pauta</h2>${list((recording.agenda||"").split("\n").filter(Boolean),"Pauta não informada.")}</section><section><h2>4. Síntese das discussões</h2><p>${esc(recording.summary||"")}</p></section><section><h2>5. Decisões</h2>${list(d.decisions,"Nenhuma decisão explícita identificada.")}</section><section><h2>6. Encaminhamentos</h2>${actionTable(recording)}</section><section><h2>7. Pendências e bloqueios</h2>${list([...d.pending,...d.blockers],"Nenhuma pendência ou bloqueio identificado.")}</section><div class="signatures"><span>Responsável pela ata</span><span>Coordenação/chefia</span></div>`,
  resumo:`<div class="executive"><h2>Visão geral</h2><p>${esc(recording.summary||"")}</p></div><section><h2>Decisões-chave</h2>${list(d.decisions,"Nenhuma decisão explícita identificada.")}</section><section><h2>Próximos passos</h2>${actionTable(recording)}</section><section><h2>Riscos e pontos de atenção</h2>${list([...d.pending,...d.blockers],"Nenhum risco explícito identificado.")}</section>`,
  acoes:`<section><h2>Plano de ação consolidado</h2>${actionTable(recording)}</section><section class="note"><h2>Critérios</h2><p>Responsáveis e prazos não mencionados na conversa permanecem sinalizados para confirmação.</p></section>`,
  decisoes:`<div class="columns"><section><h2>Decisões tomadas</h2>${list(d.decisions,"Nenhuma decisão explícita identificada.")}</section><section><h2>Pontos pendentes</h2>${list(d.pending,"Nenhuma pendência explícita identificada.")}</section><section><h2>Bloqueios e riscos</h2>${list(d.blockers,"Nenhum bloqueio explícito identificado.")}</section></div>`
 };
 const html=`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>${esc(labels[kind])} — ${esc(recording.name)}</title><style>${styles}</style></head><body><header><img src="${location.origin}/ifsc-logo.png"><div class="brand"><b>KeyNotes<span>AI</span></b><small>INTELIGÊNCIA PARA REUNIÕES</small></div><img src="${location.origin}/inovalab-logo.png"></header><div class="rule"></div><main><p class="kicker">DOCUMENTO INSTITUCIONAL</p><h1>${esc(labels[kind])}</h1><h3>${esc(recording.name)}</h3><div class="meta"><span>${esc(recording.meetingDate||recording.createdAt)}</span><span>${esc(recording.meetingTime||"Horário não informado")}</span><span>${esc(recording.department||"Setor não informado")}</span></div>${sections[kind]}</main><footer><span>Gerado pelo KeyNotesAI</span><span>INOVALAB · IFSC Câmpus Florianópolis-Continente</span></footer><script>window.addEventListener('load',()=>setTimeout(()=>window.print(),500))<\/script></body></html>`;
 const win=window.open("","_blank");if(!win){alert("Permita pop-ups para abrir o documento.");return}win.document.write(html);win.document.close();
}
function actionTable(r:DeviceRecording){const actions=r.actions||[];if(!actions.length)return`<p class="empty">Nenhuma ação explícita identificada.</p>`;return`<table><thead><tr><th>Ação</th><th>Responsável</th><th>Prazo</th><th>Prioridade</th></tr></thead><tbody>${actions.map(a=>`<tr><td>${esc(a.task)}</td><td>${esc(a.person)}</td><td>${esc(a.due)}</td><td><span class="priority">${esc(a.priority)}</span></td></tr>`).join("")}</tbody></table>`}
const styles=`@page{size:A4;margin:16mm}*{box-sizing:border-box}body{margin:0;color:#20231f;font:11pt Arial,sans-serif;background:#fff}header{display:flex;align-items:center;justify-content:space-between;height:58px}header img:first-child{width:150px;height:52px;object-fit:contain;object-position:left center}header img:last-child{width:115px;height:48px;object-fit:contain}.brand{text-align:center}.brand b{font-size:17px}.brand b span{color:#b98b4e}.brand small{display:block;font-size:6.5pt;letter-spacing:1.4px;color:#777}.rule{height:4px;background:linear-gradient(90deg,#3f765e 0 65%,#b98b4e 65%)}main{min-height:235mm;padding:18mm 5mm 12mm}.kicker{font-size:7pt;letter-spacing:2px;color:#9a7545;font-weight:bold;margin:0 0 7px}h1{font:30pt Georgia,serif;margin:0;color:#18231d}h3{font:16pt Georgia,serif;font-weight:normal;color:#536158;margin:7px 0 12px}.meta{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:18px}.meta span{background:#eef3ef;color:#42604f;border-radius:20px;padding:6px 10px;font-size:8pt}section{margin:17px 0;break-inside:avoid}h2{font:15pt Georgia,serif;border-bottom:1px solid #dfe5df;padding-bottom:6px;color:#263b2f}p,li{line-height:1.55}ul{padding-left:19px}.info{display:grid;grid-template-columns:1fr 1fr;gap:10px}.info p{background:#f6f7f4;padding:10px;margin:0}.info b{display:block;font-size:7pt;text-transform:uppercase;letter-spacing:1px;color:#987442;margin-bottom:5px}table{width:100%;border-collapse:collapse;font-size:9pt}th{text-align:left;background:#263b2f;color:#fff;padding:8px}td{padding:8px;border-bottom:1px solid #dfe4df;vertical-align:top}.priority{background:#f2eadb;color:#805f32;border-radius:12px;padding:4px 7px}.executive{background:#eef3ef;border-left:5px solid #3f765e;padding:15px 18px;margin:18px 0}.columns{display:grid;grid-template-columns:1fr;gap:8px}.columns section{border:1px solid #dfe4df;border-radius:8px;padding:12px 16px}.note{background:#fbf6ed;padding:12px 16px}.empty{color:#858982;font-style:italic}.signatures{display:grid;grid-template-columns:1fr 1fr;gap:50px;margin-top:45px}.signatures span{border-top:1px solid #777;padding-top:7px;text-align:center;font-size:8pt}footer{display:flex;justify-content:space-between;border-top:1px solid #d9ddd9;padding:8px 5mm;color:#777;font-size:7pt}@media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact}}`;
