"use client";
import{useCallback,useEffect,useState}from"react";
type Choice={id:string;name:string};
type SavedDestination={boardId:string;boardName:string;listId:string;listName:string};
export default function TrelloIntegrationPanel({isAdmin,notify}:{isAdmin:boolean;notify:(message:string)=>void}){
 const[ready,setReady]=useState(false),[boards,setBoards]=useState<Choice[]>([]),[lists,setLists]=useState<Choice[]>([]),[boardId,setBoardId]=useState(""),[listId,setListId]=useState(""),[loading,setLoading]=useState(true),[saved,setSaved]=useState<SavedDestination|null>(null);
 const load=useCallback(async()=>{setLoading(true);const response=await fetch("/api/trello/status"),status=await response.json();if(!response.ok){notify(status.error||"Não foi possível consultar o Trello");setLoading(false);return}setReady(status.credentialsReady);setSaved(status.settings||null);setBoardId(status.settings?.boardId||"");setListId(status.settings?.listId||"");if(isAdmin&&status.credentialsReady){const boardsResponse=await fetch("/api/admin/trello/boards"),boardsBody=await boardsResponse.json();if(boardsResponse.ok)setBoards(boardsBody.boards||[]);else notify(boardsBody.error||"Não foi possível carregar os Quadros");if(status.settings?.boardId){const listsResponse=await fetch(`/api/admin/trello/boards?boardId=${encodeURIComponent(status.settings.boardId)}`),listsBody=await listsResponse.json();if(listsResponse.ok)setLists(listsBody.lists||[])}}setLoading(false)},[isAdmin,notify]);
 useEffect(()=>{void load()},[load]);
 async function chooseBoard(id:string){setBoardId(id);setListId("");setLists([]);if(!id)return;const response=await fetch(`/api/admin/trello/boards?boardId=${encodeURIComponent(id)}`),body=await response.json();if(response.ok)setLists(body.lists||[]);else notify(body.error)}
 async function save(){const board=boards.find(x=>x.id===boardId),list=lists.find(x=>x.id===listId);if(!board||!list)return notify("Selecione o Quadro e a Lista");const response=await fetch("/api/admin/trello/settings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({boardId:board.id,boardName:board.name,listId:list.id,listName:list.name})}),body=await response.json();if(!response.ok)return notify(body.error);setSaved(body.settings);window.dispatchEvent(new CustomEvent("keynotesai:trello-configured",{detail:body.settings}));notify("Destino do Trello salvo")}
 const changed=!saved||saved.boardId!==boardId||saved.listId!==listId;
 return <section className="feature-page"><div className="feature-title"><div><p className="eyebrow">INTEGRAÇÕES</p><h1>Trello</h1><p>Conta institucional do INOVALAB e destino dos cards das reuniões.</p></div></div><article className="card integration-page"><div className="integration-page-head"><img src="/trello-logo.png" alt="Trello"/><div><strong>Trello institucional</strong><small>{saved?`Conectado a ${saved.boardName} → ${saved.listName}`:"Aguardando configuração"}</small></div><span className={saved?"connected":"pending"}>{saved?"Conectado":"Pendente"}</span></div>{loading?<p>Consultando integração…</p>:!ready?<div className="integration-warning"><strong>Autorização necessária</strong><p>Conecte a conta Trello do INOVALAB para liberar a seleção de Quadros e Listas.</p></div>:!isAdmin?<p>Esta integração é administrada pelo INOVALAB. Ao arquivar uma reunião no Drive, o card será sincronizado automaticamente.</p>:<div className="integration-selectors"><label><span>Quadro</span><select value={boardId} onChange={e=>void chooseBoard(e.target.value)}><option value="">Selecione…</option>{boards.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label><span>Lista</span><select value={listId} onChange={e=>setListId(e.target.value)} disabled={!boardId}><option value="">Selecione…</option>{lists.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><button onClick={save} disabled={!boardId||!listId||!changed}>{changed?(saved?"Salvar alterações":"Salvar destino"):"Destino salvo ✓"}</button></div>}</article><article className="card integration-explainer"><strong>Sincronização automática, sem duplicatas</strong><p>Ao arquivar ou atualizar a reunião no Google Drive, o KeyNotesAI cria ou atualiza automaticamente o mesmo card com resumo, decisões, ações, responsáveis, prazos, prioridades e links dos arquivos. O botão manual permanece disponível para novas alterações.</p></article></section>
}
